apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dragontts-data
  namespace: beta
  labels:
    app: dragontts
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 30Gi
